### ISSUE TITLE
java.lang.IllegalAccessError: Interface com.bc.sskr.RandomFunc implemented by class [clazz] is inaccessible

### ISSUE THREAD

**Issue by mathias21** [BlockchainCommons/bc-libs-java#4]
Hi 

After following the steps in here:
https://github.com/BlockchainCommons/bc-libs-java/blob/master/sskr/INSTALLATION.md
I couldn't find the Prebuilt aar mentioned here:

> Notice that we distribute a prebuilt aar file at prebuilt directory.

I was able to build the .aar file and include it in our project. When using the library functions, we are doing the following:

`val shards = SSKR.generate(groupThreshold, sskrDescriptors.toTypedArray(), secret, randomGenerator)`

with randomGenerator bieng:
`private val randomGenerator: (Int) -> ByteArray`

Everything compiles correctly and we can run our app. But on runtime, this exception is being thrown. 
I've checked .aar content and the interface seems to be there:
<img width="1070" alt="AarContent" src="https://user-images.githubusercontent.com/7766710/179201665-f52ce734-2ec5-440e-9ed8-bab57a82aceb.png">

I've installed OpenJDK8 just in case it was an error building the aar with other JDK. Same error, RandomFunc interface cannot be found.

We are working on Kotlin.

**Any hint here?**

**Comment by mathias21** [comment]
~~I believe the interface should be public?~~
Making the interface public solved the problem. I will prepare a PR.

**Comment by jollyjoker992** [comment]
Merged #5.
